name: Build

on:
  push:
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        makeflags: ["GENERATE_MAP=1"]
    runs-on: ubuntu-latest
    container: devkitpro/devkitppc:latest
    steps:
    - name: Install devkitPro
      run: |
        sudo dpkg --add-architecture i386
        sudo apt-get update
        sudo apt-get -y install build-essential gcc-multilib g++-multilib libc6:i386
        sudo chown $(whoami) "$GITHUB_WORKSPACE"
    - name: Checkout KAR repo
      uses: actions/checkout@v3
    - name: Checkout WiBo repo
      uses: actions/checkout@v3
      with:
        repository: decompals/WiBo
        path: tools/WiBo
    - name: Download compilers
      run: |
        curl -L https://cdn.discordapp.com/attachments/727918646525165659/917185027656286218/GC_WII_COMPILERS.zip \
          | bsdtar -xvf- -C tools --exclude Wii
        mv tools/GC tools/mwcc_compiler
    - name: Build WiBo
      working-directory: tools/WiBo
      run: |
        cmake -B build
        cmake --build build
    - name: Build map
      run: make -j$(nproc) ${{ matrix.makeflags }} WINE=./tools/WiBo/build/wibo build/kar.kor/kar.map
    - name: Upload map
      if: matrix.makeflags == 'GENERATE_MAP=1'
      uses: actions/upload-artifact@v2
      with:
        name: kar.map
        path: build/kar.kor/kar.map
    - name: Build KAR
      run: make -j$(nproc) ${{ matrix.makeflags }} WINE=./tools/WiBo/build/wibo
    - name: Calc progress
      if: matrix.makeflags == 'GENERATE_MAP=1'
      run: python3 calcprogress.py >> $GITHUB_STEP_SUMMARY
